version: "3"
services:
  sender:
    image: tugrulelmas/queue-sender
    ports:
      - "8080:80"
    environment:
      - QueueHostName=rabbitmq:5672
    depends_on:
      - rabbitmq
    deploy:
      replicas: 2
  receiver:
    image: tugrulelmas/queue-receiver
    environment:
      - QueueHostName=rabbitmq:5672
      - QueueUserName=admin
      - QueuePassword=password
    restart: on-failure
    depends_on:
      - rabbitmq
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 40s
        max_attempts: 3
  rabbitmq:
    image: rabbitmq:3.7.8-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: "abioka_rabbit"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_ERLANG_COOKIE=abioka
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8082:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
volumes:
  rabbitmq-data: