version: "3"
services:
  sender:
    image: tugrulelmas/queue-sender
    ports:
      - "8080:80"
    environment:
      - QueueHostName=rabbitmq:5672
    depends_on:
      - rabbitmq
  receiver:
    image: tugrulelmas/queue-receiver
    environment:
      - QueueHostName=rabbitmq:5672
      - QueueUserName=admin
      - QueuePassword=password
    restart: on-failure
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.7.8-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: "abioka_rabbit"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_ERLANG_COOKIE=abioka