name: Create docker images
on: [push]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: 
        - cd src
        - docker build -f Abioka.Queue.Receiver/Dockerfile -t tugrulelmas/queue-receiver:$GITHUB_SHA .
