name: Create docker images
on: [push]

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          cd src
          docker build -f Abioka.Queue.Receiver/Dockerfile -t tugrulelmas/queue-receiver:$GITHUB_SHA .
          docker build -f Abioka.Queue.Receiver/Dockerfile -t tugrulelmas/queue-receiver .
          docker build -f Abioka.Queue.Sender/Dockerfile -t tugrulelmas/queue-sender:$GITHUB_SHA .
          docker build -f Abioka.Queue.Sender/Dockerfile -t tugrulelmas/queue-sender .  
  push:
    name: Docker Push
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
     env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    needs: build
